name: Publish Javadoc on GitHub Pages

on:
    push:
        branches:
          - main
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
          - name: publish javadoc
            uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
            with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                deploy-mode: artifact
                java-version: 21
                project: gradle
