name: Publish Javadoc on GitHub Pages

on:
    push:
        branches:
          - main
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    publish-javadoc:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Setup Java
            uses: actions/setup-java@v4
            with:
                java-version: 21
                distribution: temurin
                cache: gradle

          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

          - name: Generate Javadoc
            run: ./gradlew :lib:javadoc

          - name: Deploy artifact
            uses: actions/upload-pages-artifact@v3
            with:
                path: lib/build/docs/javadoc

          - name: Deploy to GitHub Pages
            uses: actions/deploy-pages@v4
