name: Publish to GitHub Packages

on:
    release:
        types:
          - created
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    publish-pkg-github:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Java
            uses: actions/setup-java@v4
            with:
                java-version: 21
                distribution: temurin
                cache: gradle

          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

          - name: Publish package
            run: ./gradlew :lib:publish
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
